import path from "path";
import fs from "fs-extra";
import type { ExchangeType } from "@/lib/exchange";
import { resolvePersistentStorageRoot } from "@/lib/persistent-storage-root";
import type { PredictionEngineMemory, VolatilityPoint } from "@/lib/dynamic";
import moment from "moment-timezone";
import { tradeLog } from "@/lib/trading/helper/log";

const IS_RAILWAY = !!process.env.RAILWAY_ENVIRONMENT;

/**
 * Both development and production
 */
export const CACHE_DIR = resolvePersistentStorageRoot();

// PROD:STORAGE_SOURCE_OF_TRUTH
export const SLOW_TRADING_DIR = `${CACHE_DIR}/slow`;
const LEGACY_SLOW_TRADING_DIR = `${CACHE_DIR}/slow-trading`;

function slowExchangeDir(exchangeType: ExchangeType) {
  return `${SLOW_TRADING_DIR}/${exchangeType}`;
}

function slowExchangeFiles(exchangeType: ExchangeType) {
  const root = slowExchangeDir(exchangeType);

  return {
    root,
    priceNormMapOverTime: `${root}/priceNormMapOverTime.json`,
    volatility: `${root}/volatility`,
  };
}

const SLOW_FILES = {
  root: SLOW_TRADING_DIR,
  system: `${SLOW_TRADING_DIR}/system.json`,
  accounts: `${SLOW_TRADING_DIR}/accounts.json`,
  config: `${SLOW_TRADING_DIR}/config.json`,
  leaderboards: `${SLOW_TRADING_DIR}/leaderboards.json`,
  memory: `${SLOW_TRADING_DIR}/memory.json`,
  legacyState: `${SLOW_TRADING_DIR}/state.json`,
  legacyHistoryRoot: `${SLOW_TRADING_DIR}/history`,
  marketCapCache: `${SLOW_TRADING_DIR}/marketcap_cache.json`,
  notificationDedupe: `${SLOW_TRADING_DIR}/notification-dedupe.json`,
  queue: `${SLOW_TRADING_DIR}/queue.json`,
  logs: {
    errors: `${SLOW_TRADING_DIR}/logs/errors.json`,
    management: `${SLOW_TRADING_DIR}/logs/management.json`,
    safeHaven: `${SLOW_TRADING_DIR}/logs/safe_haven.json`,
    withdrawals: `${SLOW_TRADING_DIR}/logs/withdrawals.json`,
  },
  live: {
    historyRoot: `${SLOW_TRADING_DIR}/live/history`,
  },
  prod: {
    balanceSnapshots: `${SLOW_TRADING_DIR}/prod/balance_snapshots.json`,
  },
  sandbox: {
    balanceSnapshots: `${SLOW_TRADING_DIR}/sandbox/balance_snapshots.json`,
    historyRoot: `${SLOW_TRADING_DIR}/sandbox/history`,
  },

  getCachePrefix: (prefix: string) =>
    `./storage/cache/${prefix}/${moment().format("DD_MMM_YYYY_HH")}_`,

  exchange: slowExchangeFiles,
  priceNormMapOverTime: (exchangeType: ExchangeType) =>
    slowExchangeFiles(exchangeType).priceNormMapOverTime,
  volatility: (exchangeType: ExchangeType) =>
    slowExchangeFiles(exchangeType).volatility,

  volatilityPoints: {
    // save: async (exchangeType: ExchangeType, symbol: string, volatilityPoints: VolatilityPoint[]) => {
    //   await fs.writeJson(`${FILES.slow.volatility(exchangeType)}/${symbol}.json`, volatilityPoints);
    // },

    get: async (
      exchangeType: ExchangeType,
      symbol: string,
    ): Promise<VolatilityPoint[]> => {
      try {
        const memory = (await fs.readJson(
          `${FILES.slow.volatility(exchangeType)}/${symbol}.json`,
        )) as PredictionEngineMemory;

        return memory.lastVolatility;
      } catch {
        return [];
      }
    },
  },
} as const;

export const FILES = {
  slow: SLOW_FILES,
} as const;

export const FOLDER = {
  development: {
    btest: "src/__dev__/storage/development/backtest-volatility",
  },
  production: {
    autoGenerated: "src/__dev__/storage/production/auto-generated",
    btest: "src/__dev__/storage/production/backtest-volatility",
  },
};

async function main() {
  await fs.ensureDir(CACHE_DIR);
  await migrateLegacyStorage();
  await fs.ensureDir(SLOW_TRADING_DIR);
  await fs.ensureDir(path.dirname(FILES.slow.marketCapCache));

  for (const ex of ["tokocrypto", "okx", "binance"]) {
    await removeDirIfEmpty(FILES.slow.exchange(ex as ExchangeType).volatility);
    await removeDirIfEmpty(slowExchangeDir(ex as ExchangeType));
  }

  if (!IS_RAILWAY) {
    await fs.ensureDir("src/__dev__/storage/development/backtest-volatility");
    await fs.ensureDir("src/__dev__/storage/production/backtest-volatility");
    await fs.ensureDir("src/__dev__/storage/production/auto-generated");
  }
}

async function moveIfNeeded(from: string, to: string) {
  if ((await fs.pathExists(from)) && !(await fs.pathExists(to))) {
    await fs.ensureDir(path.dirname(to));
    await fs.move(from, to, { overwrite: false });
  }
}

async function migrateLegacyStorage() {
  await moveIfNeeded(LEGACY_SLOW_TRADING_DIR, SLOW_TRADING_DIR);
  await moveIfNeeded(`${CACHE_DIR}/system.json`, FILES.slow.system);
  await moveIfNeeded(
    `${CACHE_DIR}/marketcap_cache.json`,
    FILES.slow.marketCapCache,
  );

  for (const ex of ["tokocrypto", "okx", "binance"]) {
    await moveIfNeeded(
      `${CACHE_DIR}/${ex}`,
      slowExchangeDir(ex as ExchangeType),
    );
  }
}

async function removeDirIfEmpty(dir: string) {
  const exists = await fs.pathExists(dir);
  if (!exists) {
    return;
  }

  const entries = await fs.readdir(dir).catch(() => []);
  if (entries.length === 0) {
    await fs.remove(dir);
  }
}

main().catch((error) => {
  tradeLog.error(error);
});
